### ISSUE TITLE
Unable to download package

### ISSUE THREAD

**Issue by karanrajpal14** [kashav/ded#1]
I just wanted to give this a whirl on my Ubuntu machine and I'm unable to install it. 
```
karan@karan-ubuntu:~$ go get -u -v github.com/kshvmdn/ded/cmd/dep
github.com/kshvmdn/ded (download)
package github.com/kshvmdn/ded/cmd/dep: cannot find package "github.com/kshvmdn/ded/cmd/dep" in any of:
	/snap/go/1016/src/github.com/kshvmdn/ded/cmd/dep (from $GOROOT)
	/home/karan/go/src/github.com/kshvmdn/ded/cmd/dep (from $GOPATH)
```

Is it possible that the URL is incorrect? Because when I explicitly did try to open the URL, it to me to GitHub's 'not found' page.

**Comment by kashav** [comment]
> Is it possible that the URL is incorrect?

Haha, yeah. Should be `github.com/kshvmdn/ded/cmd/ded` (not `dep`).

Thanks for bringing this up 😅, feel free to open a PR to fix this.

**Comment by karanrajpal14** [comment]
Done. I should've noticed it. Should stop copy-pasting everything :P
